FROM ubuntu:14.04
ADD envconsul.cnf /opt/
ADD docker_setenv.sh /opt/


RUN sudo -E apt-get update
RUN sudo -E apt-get install -y python-software-properties software-properties-common
RUN sudo -E add-apt-repository -y ppa:webupd8team/java
RUN sudo -E apt-get update
RUN sudo -E apt-get install -y unzip
RUN sudo -E apt-get install -y wget

RUN echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
RUN sudo -E apt-get install -y oracle-java8-installer


RUN wget https://github.com/hashicorp/envconsul/releases/download/v0.6.0/envconsul_0.6.0_linux_amd64.zip -O /envconsul.zip
RUN unzip /envconsul.zip -d /usr/local/bin
RUN rm /envconsul.zip

RUN rm -rf /var/lib/{apt,dpkg,cache,log}/
RUN rm -rf /var/cache

